#!/bin/sh
TOOLS_DIR=../../tools
node $TOOLS_DIR/upload_config/run.js ../../localConfig.json <site_name>
node $TOOLS_DIR/deploy_web_job/run.js . --job-type=continuous --job-name=twitter_ingest --site-name=
