#!/bin/sh
TOOLS_DIR=../../pct-webjobtemplate/tools
#node $TOOLS_DIR/uploadConfig/run.js ../../localConfig.json pct-geotwit
node $TOOLS_DIR/deployWebJob/run.js . --job-type=continuous --job-name=twitter_ingest --site-name=pct-geotwit
